ql-qlf: qlf_k6n10f: add TDP_BRAM36 simulation models
SymbiFlow/yosys-f4pga-plugins pull request #235
Opened 2022-02-18 09:39 UTC by lpawelcz

This PR adds to ql-qlf plugin simulation models for True Dual Port Block RAMs for simulations targeting `qlf_k6n10f` devices.
The main module replaces old `TDP_BRAM36` in `cells_sim.v`. Other modules that are used inside `TDP_BRAM36` are placed in separate files: `TDP18Kx18_FIFO.v`, `sram1024x18.v`, `ufifo_ctl.v` in the same directory.

Signed-off-by: Paweł Czarnecki <pczarnecki@antmicro.com>

2022-02-21 10:26 UTC, mkurc-ant requested changes

2022-02-21 10:26 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> -    parameter INITP_00 = 256'h0000000000000000000000000000000000000000000000000000000000000000;
I think that we should keep the content initialization parameters.

2022-02-21 10:26 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
>  module TDP_BRAM36 (
Does this module match the site (pb_type) in the VPR architecture? Is there a need for further techmapping to convert it into a matching one ?

2022-02-21 11:11 UTC, lpawelcz commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
>  module TDP_BRAM36 (
@tpagarani please have a look at this. I'm not sure what is the correct `TDP_BRAM36` module ports definition: the one added here or the one from VPR architecture file?

2022-02-21 11:51 UTC, lpawelcz commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> +	CLK_A1,
Added attributes before all clocks definitions that were introduced in this PR.

2022-02-21 11:51 UTC, lpawelcz commented on ql-qlf-plugin/qlf_k6n10f/TDP18Kx18_FIFO.v
> +	CLK_A,
Added attributes before all clocks definitions that were introduced in this PR

2022-02-21 11:51 UTC, lpawelcz commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> -    parameter INITP_00 = 256'h0000000000000000000000000000000000000000000000000000000000000000;
Reintroduced `INIT` parameters

2022-02-28 13:15 UTC, lpawelcz commented
I updated the simulation models according to the newest RTL code. It was successfully tested in simulation with 4 different BRAM configurations from design: https://github.com/QuickLogic-Corp/ql_designs/blob/master/bram/bram.v

2022-03-08 03:58 UTC, rakeshm75 commented
I have been running few tests with the RAM simulation model. I found an issue with the FIFO flags. I am using fifo_1024x36, initially I push 12 data (36-bit) and pop 12 data (36-bit), the fifo flags works fine.

Then I push 1024 data (36-bit) & I see the full flag going high correctly. But when I pop out 1024 data (36-bit) I don't see the empty flag going high again. On debug, I see that the raddr is not wrapping around at the 1024 (0xffc) boundary.

[fifo_1024_36.zip](https://github.com/SymbiFlow/yosys-f4pga-plugins/files/8202615/fifo_1024_36.zip)

2022-03-08 10:26 UTC, rakeshm75 commented
We can merge the PR and continue to work on the BRAM simulation model. Approved.

2022-03-08 11:05 UTC, mkurc-ant commented
Ok. I'm merging this one.

2022-03-08 11:06 UTC, merged